export type PaymentPlaceBatch = {
  id: string;
  fileName: string;
  importedByName?: string | null;
  importedByEmail?: string | null;
  importedAt: string;
  status: string;
  totalEntries: number;
  auditEntries: number;
  unlocatedAgencyEntries: number;
  errorMessage?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
};

export type PaymentPlaceAiAnalysis = {
  available?: boolean;
  suggestion?: string | null;
  confidence?: string | null;
  summary?: string | null;
  factorsFor?: string[] | null;
  factorsAgainst?: string[] | null;
  recommendation?: string | null;
};

export type PaymentPlaceEntry = {
  id: string;
  batchId: string;
  section: string;
  externalId: string;
  clientCode?: string | null;
  titleNumber?: string | null;
  dueDate?: string | null;
  titleValue?: string | null;
  paidValue?: string | null;
  occurrence?: string | null;
  payerDocument?: string | null;
  payerName?: string | null;
  clientCity?: string | null;
  agencyCityPdf?: string | null;
  payerCity?: string | null;
  bankAgency?: string | null;
  bankCode?: string | null;
  agencyCode?: string | null;
  occurrenceComplement?: string | null;
  analysisStatus: string;
  analystDecision?: "SACADO" | "CEDENTE" | null;
  analystNotes?: string | null;
  decidedByName?: string | null;
  decidedAt?: string | null;
  bankName?: string | null;
  bacenAgencyName?: string | null;
  bacenInstitutionName?: string | null;
  bacenInstitutionType?: string | null;
  institutionCategory?: "TRADICIONAL" | "DIGITAL" | "COOPERATIVA" | "FINANCEIRA" | "INDETERMINADA" | null;
  geographicReliability?: "ALTA" | "MEDIA" | "BAIXA" | "INDETERMINADA" | null;
  geographicReliabilityReason?: string | null;
  automaticSuggestion?: "PROVAVEL_SACADO" | "PROVAVEL_CEDENTE" | "INCONCLUSIVO" | null;
  automaticConfidence?: "ALTA" | "MEDIA" | "BAIXA" | null;
  automaticEvidence?: string | null;
  scoreSacado?: number | null;
  scoreCedente?: number | null;
  aiAnalysis?: PaymentPlaceAiAnalysis | null;
  aiAnalyzedAt?: string | null;
  bacenAgencyCity?: string | null;
  bacenAgencyAddress?: string | null;
  bacenAgencyZipCode?: string | null;
  distanceClientAgencyKm?: number | null;
  distanceAgencyPayerKm?: number | null;
  distanceClientPayerKm?: number | null;
  clientLatitude?: number | null;
  clientLongitude?: number | null;
  agencyLatitude?: number | null;
  agencyLongitude?: number | null;
  payerLatitude?: number | null;
  payerLongitude?: number | null;
  clientAddress?: string | null;
  clientName?: string | null;
  clientDocument?: string | null;
  payerAddress?: string | null;
  agencyAddressResolved?: string | null;
  agencyEnrichedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
};

export type PaymentPlaceBatchDetail = {
  batch: PaymentPlaceBatch;
  entries: PaymentPlaceEntry[];
};
